<?php

//DICCIONARIO CON 20 ENTRADAS EN CASTELLANO
$arrayCastellano = [
    ["Pantera", "Leopardo, especialmente el de pelaje negro"],
    ["Despierto", "Avisado, advertido, vivo"],
    ["Diván", "Asiento alargado, generalmente sin respaldo, para recostarse o tumbarse"],
    ["Irracional", "Que carece de razón"],
    ["Hijastra", "Hijo aportado al nuevo matrimonio por el cónyuge de una persona"],
    ["Nocturno", "Perteneciente o relativo a la noche"],
    ["Adivinanza", "Acción de adivinar"],
    ["Discoteca", "Colección de discos musicales o sonoros"],
    ["Ciclomotor", "Bicicleta con motor de pequeña cilindrada, que no puede alcanzar mucha velocidad"],
    ["Aljibe", "Embarcación acondicionada para el transporte de agua dulce"],
     ["Marcador", "Tablero colocado en un lugar visible de los recintos deportivos, en el cual se anotan los tantos, puntos o lugares que van obteniendo los equipos o participantes que compiten"],
     ["Alhaja", "Adorno o mueble precioso"],
     ["Marioneta", "Persona que se deja manejar"],
     ["Incendio", "Fuego grande que destruye lo que no debería quemarse"],
     ["Positivo", "Cierto, efectivo, verdadero y que no ofrece duda"],
     ["Archivar", "Guardar documentos o información en un archivo"],
     ["Mejilla", "Cada una de las dos prominencias que hay en el rostro humano debajo de los ojos"],
     ["Rabia", "Enfermedad que se produce en algunos animales y se transmite por mordedura a otros o al hombre, al inocularse el virus por la saliva o baba del animal rabioso"],
     ["Alfiler", "Clavo metálico muy fino, que sirve generalmente para prender o sujetar alguna parte de los vestidos, los tocados y otros adornos de la persona"],
     ["Mendigo", "Persona que habitualmente pide limosna"],
];

//DICCIONARIO CON 20 ENTRADAS EN INGLÉS
$arrayIngles = [
   ["Panther", "Leopard, especially the one with black fur"],
   ["Awake", "Warned, Warned, Alive"],
   ["Divan", "Long seat, generally without a backrest, for reclining or lying down"],
   ["Irrational", "Unreasonable"],
   ["Stepdaughter", "Child brought to the new marriage by a person's spouse"],
   ["Night", "Of or relative to the night"],
   ["Riddle", "Guess Action"],
   ["Discotheque", "Collection of musical or sound records"],
   ["Moped", "Bicycle with a small displacement motor, which cannot reach a lot of speed"],
   ["Aljibe", "Boat equipped for the transport of fresh water"],
    ["Scoreboard", "Board placed in a visible place in the sports venues, in which the goals, points or places obtained by the competing teams or participants are recorded"],
    ["Jewelry", "Precious ornament or piece of furniture"],
    ["Puppet", "Person who can be manipulated"],
    ["Fire", "Big fire that destroys what should not burn"],
    ["Positive", "Certain, effective, true and that offers no doubt"],
    ["Archive", "Save documents or information to a file"],
    ["Cheek", "Each of the two prominences on the human face below the eyes"],
    ["Rabies", "Disease that occurs in some animals and is transmitted by bites to others or to humans, when the virus is inoculated by the saliva or drool of the rabid animal"],
    ["Pin", "Very fine metallic nail, which is generally used to attach or hold some part of the person's clothes, headdresses and other adornments"],
    ["Beggar", "Person who habitually asks for alms"],
];

//DICCIONARIO CON 20 ENTRADAS EN FRANCÉS
$arrayFrances = [
    ["Panthère", "Léopard, surtout celui à fourrure noire"],
    ["Éveillé", "Averti, Averti, Vivant"],
    ["Divan", "Siège long, généralement sans dossier, pour s'allonger ou s'allonger"],
    ["Irrationnel", "Déraisonnable"],
    ["Belle-fille", "Enfant amené au nouveau mariage par le conjoint d'une personne"],
    ["Nuit", "De ou se rapportant à la nuit"],
    ["Devinette", "Devinez l'action"],
    ["Discothèque", "Collection de disques musicaux ou sonores"],
    ["Cyclomoteur", "Vélo avec un moteur de petite cylindrée, qui ne peut pas atteindre beaucoup de vitesse"],
    ["Aljibe", "Bateau équipé pour le transport d'eau douce"],
     ["Scoreboard", "Panneau placé à un endroit visible dans les enceintes sportives, dans lequel sont enregistrés les buts, points ou places obtenus par les équipes en compétition ou les participants"],
     ["Bijou", "Parure ou meuble précieux"],
     ["Marionnette", "Personne manipulable"],
     ["Feu", "Grand feu qui détruit ce qui ne doit pas brûler"],
     ["Positif", "Certain, efficace, vrai et qui n'offre aucun doute"],
     ["Archive", "Enregistrer des documents ou des informations dans un fichier"],
     ["Joue", "Chacune des deux proéminences du visage humain sous les yeux"],
     ["Rage", "Maladie qui survient chez certains animaux et se transmet par morsure à d'autres ou à l'homme, lorsque le virus est inoculé par la salive ou la bave de l'animal enragé"],
     ["Epingle", "Clou métallique très fin, qui est généralement utilisé pour attacher ou maintenir une partie des vêtements, coiffes et autres ornements de la personne"],
     ["Mendiant", "Personne qui demande habituellement l'aumône"],
];

?>
