<?php

//DICCIONARIO CON 20 ENTRADAS EN CASTELLANO

$arrayCastellano = [
    ["Pantera", "Leopardo, especialmente el de pelaje negro"],
    ["Despierto", "Avisado, advertido, vivo"],
    ["Diván", "Asiento alargado, generalmente sin respaldo, para recostarse o tumbarse"],
    ["Irracional", "Que carece de razón"],
    ["Hijastra", "Hijo aportado al nuevo matrimonio por el cónyuge de una persona"],
    ["Nocturno", "Perteneciente o relativo a la noche"],
    ["Adivinanza", "Acción de adivinar"],
    ["Discoteca", "Colección de discos musicales o sonoros"],
    ["Ciclomotor", "Bicicleta con motor de pequeña cilindrada, que no puede alcanzar mucha velocidad"],
    ["Aljibe", "Embarcación acondicionada para el transporte de agua dulce"],
     ["Marcador", "Tablero colocado en un lugar visible de los recintos deportivos, en el cual se anotan los tantos, puntos o lugares que van obteniendo los equipos o participantes que compiten"],
     ["Alhaja", "Adorno o mueble precioso"],
     ["Marioneta", "Persona que se deja manejar"],
     ["Incendio", "Fuego grande que destruye lo que no debería quemarse"],
     ["Positivo", "Cierto, efectivo, verdadero y que no ofrece duda"],
     ["Archivar", "Guardar documentos o información en un archivo"],
     ["Mejilla", "Cada una de las dos prominencias que hay en el rostro humano debajo de los ojos"],
     ["Rabia", "Enfermedad que se produce en algunos animales y se transmite por mordedura a otros o al hombre, al inocularse el virus por la saliva o baba del animal rabioso"],
     ["Alfiler", "Clavo metálico muy fino, que sirve generalmente para prender o sujetar alguna parte de los vestidos, los tocados y otros adornos de la persona"],
     ["Mendigo", "Persona que habitualmente pide limosna"],
];
?>
